name = "sistema-econ-3e2"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "sistema-econ-3e2-db"
database_id = "d4dbfbc9-afb9-4116-b577-446cdea6b608"